# Setup
title:        FairTalk
tagline:      Presentación de FairCoop
baseurl:      "https://pewen.github.io/fairtalk/"
paginate:     1
encoding:     utf-8

# About/contact
author:
  name:       dbellomo
  url:        http://yourhomepage.com 

# Gems
#gems:
#  - jekyll-paginate

#Others
markdown: kramdown
